# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: './app/pom.xml'
    goals: 'package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    codeCoverageToolOption: 'Cobertura'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**/*.class'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- checkout: self
  persistCredentials: true
  clean: true

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      git --version
      New-Item -Path "$(Build.ArtifactStagingDirectory)" -Value "This is a text string."
      Write-Host "new file created, now adding file to git"
      git add -A
      Write-Host "setup author info"
      git config user.email mrz03@mail.aub.edu
      git config user.name "MarioZouein"
      Write-Host "git commit with message"
      git commit -a -m "Test Commit from Azure DevOps"
      Write-Host "git push"
      git push
    ignoreLASTEXITCODE: true